HTML_TEXT="""
<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?ADCTvvHgYKuuqwY5ti39">
        <link rel="shortcut icon" href="favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
        <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
              <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a href="login?goto=news">login</a>
                          </span></td>
              </tr></table></td></tr>
<tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tr class='athing' id='23560071'>
      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23560071' href='vote?id=23560071&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.reuters.com/article/us-alphabet-google-chrome-exclusive/exclusive-massive-spying-on-users-of-googles-chrome-shows-new-security-weakness-idUSKBN23P0JO" class="storylink">Massive spying on users of Google's Chrome shows new security weakness</a><span class="sitebit comhead"> (<a href="from?site=reuters.com"><span class="sitestr">reuters.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23560071">244 points</span> by <a href="user?id=commoner" class="hnuser">commoner</a> <span class="age"><a href="item?id=23560071">3 hours ago</a></span> <span id="unv_23560071"></span> | <a href="hide?id=23560071&amp;goto=news">hide</a> | <a href="item?id=23560071">136&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23561113'>
      <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23561113' href='vote?id=23561113&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.andyibanez.com/posts/please-help-apple-threatening-terminate-apple-developer-account/" class="storylink">Please help apple threatening terminate apple developer account</a><span class="sitebit comhead"> (<a href="from?site=andyibanez.com"><span class="sitestr">andyibanez.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23561113">23 points</span> by <a href="user?id=bpg_92" class="hnuser">bpg_92</a> <span class="age"><a href="item?id=23561113">21 minutes ago</a></span> <span id="unv_23561113"></span> | <a href="hide?id=23561113&amp;goto=news">hide</a> | <a href="item?id=23561113">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23548891'>
      <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23548891' href='vote?id=23548891&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.nutsvolts.com/magazine/article/the_magnetic_amplifier" class="storylink">The Magnetic Amplifier – A Lost Technology of the 1950s</a><span class="sitebit comhead"> (<a href="from?site=nutsvolts.com"><span class="sitestr">nutsvolts.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23548891">145 points</span> by <a href="user?id=segfaultbuserr" class="hnuser">segfaultbuserr</a> <span class="age"><a href="item?id=23548891">6 hours ago</a></span> <span id="unv_23548891"></span> | <a href="hide?id=23548891&amp;goto=news">hide</a> | <a href="item?id=23548891">33&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23557998'>
      <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23557998' href='vote?id=23557998&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://hot3eed.github.io/snap_part1_obfuscations.html" class="storylink">Reverse Engineering Snapchat: Obfuscation Techniques</a><span class="sitebit comhead"> (<a href="from?site=hot3eed.github.io"><span class="sitestr">hot3eed.github.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23557998">320 points</span> by <a href="user?id=3eed" class="hnuser">3eed</a> <span class="age"><a href="item?id=23557998">9 hours ago</a></span> <span id="unv_23557998"></span> | <a href="hide?id=23557998&amp;goto=news">hide</a> | <a href="item?id=23557998">95&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23549342'>
      <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23549342' href='vote?id=23549342&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://philosophyforprogrammers.blogspot.com/2013/06/a-graphical-introduction-to-lattices.html" class="storylink">A Graphical Introduction to Lattices</a><span class="sitebit comhead"> (<a href="from?site=philosophyforprogrammers.blogspot.com"><span class="sitestr">philosophyforprogrammers.blogspot.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23549342">37 points</span> by <a href="user?id=nickysielicki" class="hnuser">nickysielicki</a> <span class="age"><a href="item?id=23549342">3 hours ago</a></span> <span id="unv_23549342"></span> | <a href="hide?id=23549342&amp;goto=news">hide</a> | <a href="item?id=23549342">5&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23558686'>
      <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23558686' href='vote?id=23558686&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://librivox.org/" class="storylink">LibriVox: Free Public Domain Audiobooks</a><span class="sitebit comhead"> (<a href="from?site=librivox.org"><span class="sitestr">librivox.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23558686">161 points</span> by <a href="user?id=drummer" class="hnuser">drummer</a> <span class="age"><a href="item?id=23558686">8 hours ago</a></span> <span id="unv_23558686"></span> | <a href="hide?id=23558686&amp;goto=news">hide</a> | <a href="item?id=23558686">37&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23550409'>
      <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23550409' href='vote?id=23550409&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://slate.com/news-and-politics/2010/06/into-thin-error-mountaineer-ed-viesturs-on-making-mistakes.html" class="storylink">Into Thin Error: Mountaineer Ed Viesturs on Making Mistakes</a><span class="sitebit comhead"> (<a href="from?site=slate.com"><span class="sitestr">slate.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23550409">9 points</span> by <a href="user?id=ColinWright" class="hnuser">ColinWright</a> <span class="age"><a href="item?id=23550409">1 hour ago</a></span> <span id="unv_23550409"></span> | <a href="hide?id=23550409&amp;goto=news">hide</a> | <a href="item?id=23550409">1&nbsp;comment</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23549203'>
      <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23549203' href='vote?id=23549203&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://web.mit.edu/curhan/www/docs/Articles/15341_Readings/Motivation/Kerr_Folly_of_rewarding_A_while_hoping_for_B.pdf" class="storylink">On the Folly of Rewarding A, While Hoping for B (1975) [pdf]</a><span class="sitebit comhead"> (<a href="from?site=web.mit.edu"><span class="sitestr">web.mit.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23549203">63 points</span> by <a href="user?id=Someone" class="hnuser">Someone</a> <span class="age"><a href="item?id=23549203">6 hours ago</a></span> <span id="unv_23549203"></span> | <a href="hide?id=23549203&amp;goto=news">hide</a> | <a href="item?id=23549203">13&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23537283'>
      <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23537283' href='vote?id=23537283&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.theparisreview.org/blog/2016/09/21/who-the-hell-is-this-joyce/" class="storylink">Who the Hell Is This Joyce (1928)</a><span class="sitebit comhead"> (<a href="from?site=theparisreview.org"><span class="sitestr">theparisreview.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23537283">98 points</span> by <a href="user?id=s_dev" class="hnuser">s_dev</a> <span class="age"><a href="item?id=23537283">7 hours ago</a></span> <span id="unv_23537283"></span> | <a href="hide?id=23537283&amp;goto=news">hide</a> | <a href="item?id=23537283">57&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23560487'>
      <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23560487' href='vote?id=23560487&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.cnil.fr/en/cnil-publishes-gdpr-guide-developers" class="storylink">GDPR guide for developers</a><span class="sitebit comhead"> (<a href="from?site=cnil.fr"><span class="sitestr">cnil.fr</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23560487">91 points</span> by <a href="user?id=homarp" class="hnuser">homarp</a> <span class="age"><a href="item?id=23560487">2 hours ago</a></span> <span id="unv_23560487"></span> | <a href="hide?id=23560487&amp;goto=news">hide</a> | <a href="item?id=23560487">36&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23538028'>
      <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23538028' href='vote?id=23538028&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://archive.org/details/FarewellEtaoinShrdlu" class="storylink">Farewell Etaoin Shrdlu (1978) [video]</a><span class="sitebit comhead"> (<a href="from?site=archive.org"><span class="sitestr">archive.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23538028">49 points</span> by <a href="user?id=truxs" class="hnuser">truxs</a> <span class="age"><a href="item?id=23538028">6 hours ago</a></span> <span id="unv_23538028"></span> | <a href="hide?id=23538028&amp;goto=news">hide</a> | <a href="item?id=23538028">19&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23554944'>
      <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23554944' href='vote?id=23554944&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://openai.com/blog/image-gpt/" class="storylink">Image GPT</a><span class="sitebit comhead"> (<a href="from?site=openai.com"><span class="sitestr">openai.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23554944">255 points</span> by <a href="user?id=todsacerdoti" class="hnuser">todsacerdoti</a> <span class="age"><a href="item?id=23554944">14 hours ago</a></span> <span id="unv_23554944"></span> | <a href="hide?id=23554944&amp;goto=news">hide</a> | <a href="item?id=23554944">70&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23560850'>
      <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td></td><td class="title"><a href="https://substack.com/jobs" class="storylink" rel="nofollow">Substack (YC W18) Is Hiring to Build a Better Business Model for Writing</a><span class="sitebit comhead"> (<a href="from?site=substack.com"><span class="sitestr">substack.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="age"><a href="item?id=23560850">1 hour ago</a></span> | <a href="hide?id=23560850&amp;goto=news">hide</a>      </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23554869'>
      <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23554869' href='vote?id=23554869&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://mdlayher.com/blog/go-generics-draft-design-building-a-hashtable/" class="storylink">Go generics draft design: building a hashtable</a><span class="sitebit comhead"> (<a href="from?site=mdlayher.com"><span class="sitestr">mdlayher.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23554869">175 points</span> by <a href="user?id=mdlayher" class="hnuser">mdlayher</a> <span class="age"><a href="item?id=23554869">14 hours ago</a></span> <span id="unv_23554869"></span> | <a href="hide?id=23554869&amp;goto=news">hide</a> | <a href="item?id=23554869">106&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23553325'>
      <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23553325' href='vote?id=23553325&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.zoom.us/wordpress/2020/06/17/end-to-end-encryption-update/" class="storylink">Zoom to bring end-to-end encryption to all users, including non-paying</a><span class="sitebit comhead"> (<a href="from?site=zoom.us"><span class="sitestr">zoom.us</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23553325">749 points</span> by <a href="user?id=jmsflknr" class="hnuser">jmsflknr</a> <span class="age"><a href="item?id=23553325">16 hours ago</a></span> <span id="unv_23553325"></span> | <a href="hide?id=23553325&amp;goto=news">hide</a> | <a href="item?id=23553325">446&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23535853'>
      <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23535853' href='vote?id=23535853&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.dougengelbart.org/content/view/374/464/" class="storylink">Doug Engelbart’s 1968 demo</a><span class="sitebit comhead"> (<a href="from?site=dougengelbart.org"><span class="sitestr">dougengelbart.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23535853">170 points</span> by <a href="user?id=whatrocks" class="hnuser">whatrocks</a> <span class="age"><a href="item?id=23535853">13 hours ago</a></span> <span id="unv_23535853"></span> | <a href="hide?id=23535853&amp;goto=news">hide</a> | <a href="item?id=23535853">40&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23535714'>
      <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23535714' href='vote?id=23535714&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.npr.org/sections/thesalt/2018/01/02/574367086/from-hooch-to-haute-cuisine-a-nearly-extinct-bootleggers-corn-gets-a-second-shot" class="storylink">A Nearly Extinct Bootlegger's Corn Gets a Second Shot (2018)</a><span class="sitebit comhead"> (<a href="from?site=npr.org"><span class="sitestr">npr.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23535714">73 points</span> by <a href="user?id=thesausageking" class="hnuser">thesausageking</a> <span class="age"><a href="item?id=23535714">9 hours ago</a></span> <span id="unv_23535714"></span> | <a href="hide?id=23535714&amp;goto=news">hide</a> | <a href="item?id=23535714">21&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23542876'>
      <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23542876' href='vote?id=23542876&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://loglo.app/" class="storylink">Loglo: Experimental spreadsheet and stack language for vector graphics</a><span class="sitebit comhead"> (<a href="from?site=loglo.app"><span class="sitestr">loglo.app</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23542876">150 points</span> by <a href="user?id=jashkenas" class="hnuser">jashkenas</a> <span class="age"><a href="item?id=23542876">15 hours ago</a></span> <span id="unv_23542876"></span> | <a href="hide?id=23542876&amp;goto=news">hide</a> | <a href="item?id=23542876">24&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23560823'>
      <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23560823' href='vote?id=23560823&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://lwn.net/SubscriberLink/822568/61d29096a4012e06/" class="storylink" rel="nofollow">Lightweight Alternatives to Google Analytics</a><span class="sitebit comhead"> (<a href="from?site=lwn.net"><span class="sitestr">lwn.net</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23560823">6 points</span> by <a href="user?id=Tomte" class="hnuser">Tomte</a> <span class="age"><a href="item?id=23560823">1 hour ago</a></span> <span id="unv_23560823"></span> | <a href="hide?id=23560823&amp;goto=news">hide</a> | <a href="item?id=23560823">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23556862'>
      <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23556862' href='vote?id=23556862&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://github.com/eerimoq/monolinux-jiffy#boot-time" class="storylink">Booting embedded Linux in 0.37 seconds on an ARMv7-A CPU at 528 MHz</a><span class="sitebit comhead"> (<a href="from?site=github.com"><span class="sitestr">github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23556862">129 points</span> by <a href="user?id=eerimoq" class="hnuser">eerimoq</a> <span class="age"><a href="item?id=23556862">11 hours ago</a></span> <span id="unv_23556862"></span> | <a href="hide?id=23556862&amp;goto=news">hide</a> | <a href="item?id=23556862">47&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23551983'>
      <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23551983' href='vote?id=23551983&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://tonsky.me/blog/monitors/" class="storylink">Time to Upgrade Your Monitor</a><span class="sitebit comhead"> (<a href="from?site=tonsky.me"><span class="sitestr">tonsky.me</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23551983">973 points</span> by <a href="user?id=neonbones" class="hnuser">neonbones</a> <span class="age"><a href="item?id=23551983">18 hours ago</a></span> <span id="unv_23551983"></span> | <a href="hide?id=23551983&amp;goto=news">hide</a> | <a href="item?id=23551983">821&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23550420'>
      <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23550420' href='vote?id=23550420&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://lambda-the-ultimate.org/node/2440" class="storylink" rel="nofollow">Modularizing SQL? (2007)</a><span class="sitebit comhead"> (<a href="from?site=lambda-the-ultimate.org"><span class="sitestr">lambda-the-ultimate.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23550420">17 points</span> by <a href="user?id=Kinrany" class="hnuser">Kinrany</a> <span class="age"><a href="item?id=23550420">2 hours ago</a></span> <span id="unv_23550420"></span> | <a href="hide?id=23550420&amp;goto=news">hide</a> | <a href="item?id=23550420">12&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23556841'>
      <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23556841' href='vote?id=23556841&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://berthub.eu/articles/posts/covid-19-t-cells/" class="storylink">Covid-19: The T Cell Story</a><span class="sitebit comhead"> (<a href="from?site=berthub.eu"><span class="sitestr">berthub.eu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23556841">106 points</span> by <a href="user?id=xearl" class="hnuser">xearl</a> <span class="age"><a href="item?id=23556841">11 hours ago</a></span> <span id="unv_23556841"></span> | <a href="hide?id=23556841&amp;goto=news">hide</a> | <a href="item?id=23556841">71&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23558853'>
      <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23558853' href='vote?id=23558853&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://unixism.net/2020/06/containers-the-hard-way-gocker-a-mini-docker-written-in-go/" class="storylink">Gocker: Docker implemented in 1.3k lines of Go</a><span class="sitebit comhead"> (<a href="from?site=unixism.net"><span class="sitestr">unixism.net</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23558853">120 points</span> by <a href="user?id=shuss" class="hnuser">shuss</a> <span class="age"><a href="item?id=23558853">7 hours ago</a></span> <span id="unv_23558853"></span> | <a href="hide?id=23558853&amp;goto=news">hide</a> | <a href="item?id=23558853">58&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23539332'>
      <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23539332' href='vote?id=23539332&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://mkhan45.github.io/2020/06/16/using-lua-as-a-serialization-format.html" class="storylink">Using Lua as a Serialization Format</a><span class="sitebit comhead"> (<a href="from?site=mkhan45.github.io"><span class="sitestr">mkhan45.github.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23539332">85 points</span> by <a href="user?id=fish45" class="hnuser">fish45</a> <span class="age"><a href="item?id=23539332">8 hours ago</a></span> <span id="unv_23539332"></span> | <a href="hide?id=23539332&amp;goto=news">hide</a> | <a href="item?id=23539332">59&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23558176'>
      <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23558176' href='vote?id=23558176&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.congruentlabs.co/getting-the-most-out-of-yubikeys-for-your-business/" class="storylink">Getting the most out of YubiKeys for your business</a><span class="sitebit comhead"> (<a href="from?site=congruentlabs.co"><span class="sitestr">congruentlabs.co</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23558176">56 points</span> by <a href="user?id=burrben" class="hnuser">burrben</a> <span class="age"><a href="item?id=23558176">9 hours ago</a></span> <span id="unv_23558176"></span> | <a href="hide?id=23558176&amp;goto=news">hide</a> | <a href="item?id=23558176">37&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23548640'>
      <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23548640' href='vote?id=23548640&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.potaroo.net/ispcol/2020-06/row.html" class="storylink">Where Is the DNS Headed?</a><span class="sitebit comhead"> (<a href="from?site=potaroo.net"><span class="sitestr">potaroo.net</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23548640">45 points</span> by <a href="user?id=m-app" class="hnuser">m-app</a> <span class="age"><a href="item?id=23548640">7 hours ago</a></span> <span id="unv_23548640"></span> | <a href="hide?id=23548640&amp;goto=news">hide</a> | <a href="item?id=23548640">13&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23554584'>
      <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23554584' href='vote?id=23554584&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://apolloprojects.com/" class="storylink">Apollo – Funding for Moonshots</a><span class="sitebit comhead"> (<a href="from?site=apolloprojects.com"><span class="sitestr">apolloprojects.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23554584">188 points</span> by <a href="user?id=janvdberg" class="hnuser">janvdberg</a> <span class="age"><a href="item?id=23554584">15 hours ago</a></span> <span id="unv_23554584"></span> | <a href="hide?id=23554584&amp;goto=news">hide</a> | <a href="item?id=23554584">88&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23558149'>
      <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23558149' href='vote?id=23558149&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://krebsonsecurity.com/2020/06/when-security-takes-a-backseat-to-productivity/" class="storylink">When Security Takes a Backseat to Productivity</a><span class="sitebit comhead"> (<a href="from?site=krebsonsecurity.com"><span class="sitestr">krebsonsecurity.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23558149">44 points</span> by <a href="user?id=todsacerdoti" class="hnuser">todsacerdoti</a> <span class="age"><a href="item?id=23558149">9 hours ago</a></span> <span id="unv_23558149"></span> | <a href="hide?id=23558149&amp;goto=news">hide</a> | <a href="item?id=23558149">28&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='23553689'>
      <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id='up_23553689' href='vote?id=23553689&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://aws.amazon.com/blogs/aws/introducing-aws-snowcone-small-lightweight-edge-storage-and-processing/" class="storylink">AWS Snowcone</a><span class="sitebit comhead"> (<a href="from?site=amazon.com"><span class="sitestr">amazon.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_23553689">430 points</span> by <a href="user?id=jeffbarr" class="hnuser">jeffbarr</a> <span class="age"><a href="item?id=23553689">16 hours ago</a></span> <span id="unv_23553689"></span> | <a href="hide?id=23553689&amp;goto=news">hide</a> | <a href="item?id=23553689">197&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
            <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="next">More</a></td></tr>
  </table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="mailto:hn@ycombinator.com">Support</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="lists">Lists</a>
        | <a href="bookmarklet.html" rel="nofollow">Bookmarklet</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
"""